spring:
  application:
    name: order-service

server:
  port: 9008

#微信支付配置
#wxpay:
#  appId: wxb709cf6e6a7d9d2a
#  appSecret: d9a9ff00a633cd7353a8925119063b01
#  mchId: 1473426802
#  partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
#  notifyUrl: https://572c0244.cpolar.io/wxpay/payNotify
